version: '3.3'
services:
  orion:
    image: fiware/orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    command: -dbhost mongo-db

  mongo-db:
    image: mongo:4.4
    command: --nojournal
    ports:
      - "27017:27017"

  cratedb:
    image: crate:4.5
    hostname: cratedb
    ports:
        - "4200:4200"
        - "4300:4300"
    command:
        -Ccluster.name=democluster -Chttp.cors.enabled=true
        -Chttp.cors.allow-origin="*"

  quantumleap:
    image: orchestracities/quantumleap
    hostname: quantumleap
    ports:
        - "8668:8668"
    depends_on:
        - cratedb
    environment:
        - CRATE_HOST=cratedb